title: Околотехнические заметки
description: Главное не забывать вести этот чертов бложек
author: Антон Маркелов
github: https://github.com/strangeman
about: Автоматизирую, поддерживаю, починяю примус
google_analytics: UA-44126153-3

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-telegram
      link: "https://t.me/strangeman"
    - icon: fa-facebook
      link: "https://www.facebook.com/imstrangeman"
    - icon: fa-twitter
      link: "https://twitter.com/_strangeman"
    - icon: fa-linkedin
      link: "http://linkedin.com/in/markelovanton"

share:
  twitter_username: _strangeman
  fb_appid: imstrangeman

urls:
    - text: Обо мне
      url: /about/
    - text: Resume Eng (PDF)
      url: /static/Anton-Markelov-DevOps-CV-20241225-2.pdf
    - text: Github
      url: https://github.com/strangeman
    - text: XML Feed
      url: /feed.xml

url: "https://blog.strangeman.info"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist